development:  
  adapter: sqlite3
  database: db/development.sqlite3

test:
    adapter: sqlite3
    database: ':memory:'

production:
    adapter: mysql
    database: scavenger_production
    username: root
    password:
